### PR TITLE
Support node require, fetch, and promises

### PR DESCRIPTION
**Pull request by brysgo**
Not sure if this got deleted or if I forgot to make a PR, anyways, I'd love to hear any feedback you have. I had prettier on in my editor, but I can undo the style changes if that is a problem.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@brysgo looks great. Couple of quick things:

- Assume you ran the tests - can you confirm that 😄 
- Are you happy to license under MIT?

**Comment by brysgo** [comment]
@rufuspollock 
1) did not run the tests (just put together a simple use case but probably should have run them)
  - I will run the tests and get back to you.
2) Happy to license under MIT

**Comment by brysgo** [comment]
@rufuspollock - now the tests pass ;-)

**Comment by rufuspollock** [comment]
@brysgo awesome and thank-you. If you want to do a (separate) PR to add yourself as a contributor to the README please do 😄

**Pull request merged**
